@url=http://localhost:8000/api/
@token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsImV4cCI6MTYyNDg3ODU5OX0.JtlvwVOnCZQDkrCbirFmTXAAnQ91HLWnaSF3CgI7C2A
@id = 14

#GET ALL PROJECTS
GET {{url}}projects/

###

#GET A SINGLE PROJECT
GET {{url}}projects/13/


###

#DELETE A PROJECT
DELETE {{url}}projects/9/
content-type: application/json
Authorization: Bearer {{token}}

###

#CREATE A PROJECT
POST {{url}}projects/
content-type: application/json
Authorization: Bearer {{token}}

{
  "projectName":"High Focus12332",
  "url":"https://www.high-focus.com/home/"

}


###
#CREATE A NEW USER
POST {{url}}auth/register/
content-type:application/json

{
"username":"ErrorTest",
"email":"ErrorTest@email.com",
"password":"pass",
"passwordConfirmation":"pass",
"profileImage":"https://i.imgflip.com/47n5zy.png",
"gacohort":"SEI#55",
"linkedin":"www.linkedin.com",
"github":"www.github.com",
"twitter":"www.twitter.com",
"instagram":"www.instagram.com",
"personal_site":"www.google.com",
"jobTitle":"Junior Dev"

}

###
#LOGIN USER
POST {{url}}auth/login/
content-type:application/json

{
  "email":"admin@email.com",
  "password":"admin"
}

###
#MAKE A COMMENT

POST {{url}}projects/1/comments/
content-type: application/json
Authorization: Bearer {{token}}

{
  "content":"this is a comment that im gonna delete Craig"
}

###
#DELETE COMMENT

DELETE  {{url}}projects/1/comments/1/
content-type: application/json
Authorization: Bearer {{token}}

###
#FAVORITE
POST {{url}}projects/13/favorite/
content-type: application/json
Authorization: Bearer {{token}}



###
#GET A SINGLE USER
GET {{url}}auth/profile/{{id}}/

###

PUT {{url}}auth/profile/{{id}}/
content-type: application/json
Authorization: Bearer {{token}}


{
  "username": "admin",
  "password": "admin",
  "passwordConfirmation": "admin",
  "profileImage": "https://www.pngitem.com/pimgs/m/150-1503945_transparent-user-png-default-user-image-png-png.png",
  "email": "admin@email.com",
  "favorites": [],
  "comments": [],
  "createdProject": "",
  "gacohort": "",
  "linkedin": "",
  "github": "",
  "twitter": "",
  "personalsite": "",
  "instagram": "instagram",
  "jobTitle": "Engineer"
}

###

# GET ALL users
GET {{url}}auth/profile/














