@url=http://localhost:8000/api/
@token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjYsImV4cCI6MTYyNDU1NTk1N30.vF4gqT_oC0Yk8By3a8mCm-AvEEGIcpg3ZSP2_FGKrHc
@id = 3

#GET ALL PROJECTS
GET {{url}}projects/

###

#GET A SINGLE PROJECT
GET {{url}}projects/2/


###

#DELETE A PROJECT
DELETE {{url}}projects/9/
content-type: application/json
Authorization: Bearer {{token}}

###

#CREATE A PROJECT
POST {{url}}projects/
content-type: application/json
Authorization: Bearer {{token}}

{
  "projectName":"High Focus",
  "url":"https://www.high-focus.com/home/"
  
}


###
#CREATE A NEW USER
POST {{url}}auth/register/
content-type:application/json

{
"username":"CraigClement",
"email":"craig@email.com",
"password":"pass",
"passwordConfirmation":"pass",
"profileImage":"https://i.imgflip.com/47n5zy.png",
"GAcohort":"SEI#55",
"LinkedIn":"www.linkedin.com",
"Github":"www.github.com",
"Twitter":"www.twitter.com",
"Instagram":"www.instagram.com",
"personal_site":"www.google.com"

}

###
#LOGIN USER
POST {{url}}auth/login/
content-type:application/json

{
  "email":"craig@email.com",
  "password":"pass"
}

###
#MAKE A COMMENT

POST {{url}}projects/1/comments/
content-type: application/json
Authorization: Bearer {{token}}

{
  "content":"this is a comment that im gonna delete Craig"
}

###
#DELETE COMMENT

DELETE  {{url}}projects/1/comments/1/
content-type: application/json
Authorization: Bearer {{token}}

###
#FAVORITE
POST {{url}}projects/1/favorite/
content-type: application/json
Authorization: Bearer {{token}}



###
#GET A SINGLE USER
GET {{url}}auth/profile/{{id}}/














